language: haskell

before_install:
  - cabal install 'hpc-coveralls == 0.2.1'

script:
  - cabal configure --enable-tests --enable-library-coverage
  - cabal build
  - run-cabal-test --show-details=always

after_script:
  - hpc-coveralls --exclude-dir=tests thebook-hpc
