language: haskell

before_install:
  - sudo apt-get -q -y install hlint || cabal install hlint

script:
  - cabal sandbox init
  - cabal configure --enable-tests --enable-library-coverage
  - cabal build
  - run-cabal-test --show-details=always

after_script:
  - cabal install 'hpc-coveralls >= 0.2.1'
  - hpc-coveralls --exclude-dir=tests thebook-hpc
